### ISSUE TITLE
Viewer history error

### ISSUE THREAD

**Issue by randombyte-developer** [taddeimania/lctva#21]
Hello!

Steps to reproduce:
- Click on a date in the viewer history

http://dpaste.com/1911EFY

**Comment by taddeimania** [comment]
oof this IS a major bug. Thanks for finding it. I'll get on it asap.

this should fix the bug temporarily but the videos wont show. Will work on long term solution.

https://github.com/taddeimania/lctva/commit/fda1678657ea6234349007eb35fd2b414ce734bb

**Comment by taddeimania** [comment]
This bug forced me to jump on a bit of a refactor in how I was handling auth tokens from LCTV.

The following commits happily close the issue:
https://github.com/taddeimania/lctva/commit/d5c3321ea3b586016792ddd36fa1cc66afdde5ee
https://github.com/taddeimania/lctva/commit/f3d1939ed87f72c56380aac3d66ee5e6768008a2
