### ISSUE TITLE
Cancel authorization request

### ISSUE THREAD

**Issue by randombyte-developer** [taddeimania/lctva#22]
Lctv asks me if lctva should be authorized. When I click cancel(just for fun): http://dpaste.com/0E628WM

**Comment by taddeimania** [comment]
dang you're on a roll! when I stream later tonight i've got plenty to do :)  Thanks for catching this.

**Comment by taddeimania** [comment]
https://github.com/taddeimania/lctva/commit/9cffd69e9f5a40a61ab03553d2656d026834568b closes
