### ISSUE TITLE
Missing strings in translation files

### ISSUE THREAD

**Issue by randombyte-developer** [taddeimania/lctva#25]
These strings are missing in the translation files:
- [x] "[number] min limit" in round brackets after "max viewers" in the live view of a stream
- [x] "true"/"false" after "Trending Up:" in the live view of a stream(possibly change them to "yes"/"no")
- [x] "user count" and "mean" on the right side of daily breakdown graph
- [x] "Watch me work" in the "About" view
- [x] "Total Viewers on livecoding.tv (UTC)" at the start page of lctva

**Comment by taddeimania** [comment]
https://github.com/taddeimania/lctva/commit/a48f9a411c6f4f349d283c3908286dea75724595 addresses 4/5 of the mentioned issues.

Will take a look at the true/false = yes/no weirdness now.

**Comment by taddeimania** [comment]
I just removed the "trending" metric. It never served a good purpose.
