### ISSUE TITLE
History detail error

### ISSUE THREAD

**Issue by randombyte-developer** [taddeimania/lctva#26]
Again an error when clicking on a date in the history: http://dpaste.com/26JBVQM

**Comment by taddeimania** [comment]
logging out and back in should fix it. Let me know if it doesn't.

**Comment by randombyte-developer** [comment]
No, but seems to be another error this time: http://dpaste.com/1XFD0T7

**Comment by taddeimania** [comment]
good grief it looks like LCTV may have changed their timestamp format.

**Comment by taddeimania** [comment]
Yup, when I do an API request on your behalf I get

`creation_time='2015-07-01T00:00:00'`

When I do an API request on my behalf I get

`creation_time='2016-01-20T03:56:41.050737Z'`

I'm guessing old videos didn't store the time.  I think I know a way to fix this but i'm hanging with the family right now.  If anyone wants to take a stab at it the code is here: https://github.com/taddeimania/lctva/blob/master/app/views/history.py#L40

Should probably mess with a combo of slicing the timestamp from the API so microseconds are ignored and changing the `strptime` format.

**Comment by taddeimania** [comment]
this should fix the 2nd issue on history detail page

https://github.com/taddeimania/lctva/commit/4f4a4f3689786a2bb7558ede4f1c6f259e383090

Feel free to reopen if any more errors pop up on history detail page.
